name: CI Workflow

# Trigger the workflow when code is pushed to the repository
on: [push]

jobs:
  build:
    # Use the latest Ubuntu runner
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      # This action checks out the code from the repository so it can be accessed
      uses: actions/checkout@v3
    
    - name: Print message
      # Run a shell command as part of this step
      run: echo "Hello, GitHub Actions!"
